### ISSUE TITLE
Clarify the medical letter requirements for passports

### ISSUE THREAD

**Issue by calliecameron** [genderkit/genderkit#418] opened 2022-11-17 08:21 UTC
I recently changed the gender on my passport. My medical letter was initially rejected because it didn't contain the exact words 'the change is likely to be permanent' (it said more or less the same thing in different wording).

Update the docs to say that, to be on the safe side, the medical letter should contain the exact phrase 'the change is likely to be permanent'.

**Comment by fallax** [comment] 2022-11-17 12:14
Thanks for raising this - think it is a duplicate of #359 though?

If you're happy with that I'll close this issue.

**Closed** 2022-11-20 16:38 UTC
